# import glob2 and datetime libraries
import glob2
import datetime

# use the glob library to read the file names in a directory
# in our case its the sample-files directory.
# as we have said *.txt, it will find all files in this directory that are txt
filenames = glob2.glob("*.txt")

""" open a file that if it doesnt exist create using the string from time
method from the datetime library, using %y for year, %m for month etc."""

with open(datetime.datetime.now().strftime("%Y-%m-%d-%H-%M-%S-%f")+".txt", 'w') as file:
    # for each filename in the filename list above (generated by glob)
    for filename in filenames:
        # open the file with read permissions as f
        with open(filename, "r") as f:
            # write to the file with the contents that is read adding a newline
            file.write(f.read()+"\n")
